#include "curl_utils.hpp"
#include "time_utils.hpp"

#include <curl/curl.h>
#include <algorithm>
#include <sstream>
#include <fstream>

void saveYahooCredentials(const char* filename, std::string *crumb, std::string *cookie) {
    // Open cookie file
    std::ofstream file(filename);

    // Save update time, crumb and cookie
    file << currentEpoch() << std::endl;
    file << *crumb << std::endl;
    file << *cookie << std::endl;

    // Close cookie file
    file.close();
}

std::time_t readCookieTime(const char* filename) {
    // Open cookie file
    std::ifstream file(filename);

    // Read the last cookie update time
    std::time_t date;
    file >> date;

    return date;
}

void readCrumbCredential(const char* filename, std::string *crumb) {
    // Open cookie file
    std::ifstream file(filename);

    // Read the crumb
    file >> *crumb;
    *crumb = "";
    file >> *crumb;
}

void readCookieCredential(const char* filename, std::string *cookie) {
    // Open cookie file
    std::ifstream file(filename);

    // Read the cookie
    file >> *cookie >> *cookie;
    *cookie = "";
    file >> *cookie;
}

bool needNewCookie(const char* filename, std::time_t time) {
    std::time_t currentDate = currentEpoch();
    std::time_t cookieDate = readCookieTime(filename);
    return currentDate - cookieDate > time;
}

size_t writeCallback(char *content, size_t size, size_t nmemb, void *userdata) {
    // Append the content to user data
    ((std::string*)userdata)->append(content, size * nmemb);

    // Return the real content size
    return size * nmemb;
}

void getYahooCrumbCookie(std::string url,
                         std::string *crumb,
                         std::string *cookie) {
    const char* credentialFile = "/tmp/yahoo-finance-credentials";
    const char* cookieFile = "/tmp/yahoo-finance-cookie";

    // Download new cookie every 15 minutes
    if (needNewCookie(credentialFile, 900)) {
        CURL* curl = curl_easy_init();
        std::string responseBuffer;

        if (curl) {
            curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1);
            curl_easy_setopt(curl, CURLOPT_COOKIEJAR,  cookieFile);
            curl_easy_setopt(curl, CURLOPT_URL, url.c_str());

            // Write result into the buffer
            curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeCallback);
            curl_easy_setopt(curl, CURLOPT_WRITEDATA, &responseBuffer);

            // Perform the request
            CURLcode res = curl_easy_perform(curl);

            // Cleanup
            curl_easy_cleanup(curl);
        }

        *crumb = extractYahooCrumb(responseBuffer);
        *cookie = extractYahooCookie(cookieFile);

        // Save crumb and cookie values
        saveYahooCredentials(credentialFile, crumb, cookie);
    } else {
        // Read crumb and cookie values from tmp file
        readCrumbCredential(credentialFile, crumb);
        readCookieCredential(credentialFile, cookie);
    }
}

std::string extractYahooCrumb(std::string code) {
    // Find the CrumbStore location
    size_t found = code.find("CrumbStore");

    // Get the crumb line (cut at the crumb string start)
    std::string crumbLine = code.substr(found + 22);

    // Crumb string length
    int8_t crumbSize = crumbLine.find('"');

    // Get the crumb and return
    std::string crumb = crumbLine.substr(0, crumbSize);

    // Escape U+002F character randomly generated by Yahoo
    std::replace(crumb.begin(), crumb.end(), '\u002F', '/');

    // Return the crumb
    return crumb;
}

std::string extractYahooCookie(const char* filename) {
    int i = 0;
    std::string line;
    std::ifstream file(filename);

    if (file.is_open()) {
        while (std::getline(file, line) && i < 4) {
            ++i;
        }
        file.close();
    }

    std::string cookie = "B=" + line.substr(37);
    return cookie;
}

std::string downloadYahooCsv(std::string symbol,
                             std::time_t period1,
                             std::time_t period2,
                             std::string interval,
                             std::string *crumb,
                             std::string *cookie) {
    std::stringstream ss1; 
    ss1 << period1; 
    std::stringstream ss2; 
    ss2 << period2;

    std::string url = "https://query1.finance.yahoo.com/v7/finance/download/"
            + symbol
            + "?period1=" + ss1.str()
            + "&period2=" + ss2.str()
            + "&interval=" + interval
            + "&events=history"
            + "&crumb=" + *crumb;

    CURL* curl = curl_easy_init();
    std::string responseBuffer;

    if (curl) {
        curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
        curl_easy_setopt(curl, CURLOPT_COOKIE, cookie->c_str());

        // Write result into the buffer
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writeCallback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &responseBuffer);

        // Perform the request
        CURLcode res = curl_easy_perform(curl);

        // Cleanup
        curl_easy_cleanup(curl);
    }

    return responseBuffer;
}
